### ISSUE TITLE
Install failure on redmine 3.4.11

### ISSUE THREAD

**Issue by sherpadawan** [Smile-SA/redmine_smile_base#1]
`bundle exec rake redmine:plugins:migrate RAILS_ENV=production`
```
(in /var/www/html/redmine-3.4.11)
rake aborted!
Redmine::I18n MISS    instance_methods  l_time, round_decimals, format_date_by_directives, format_date_time, format_duration, l_hours, format_hours  < (SM::RedmineOverride::I18nOverride::Enhancements)
/var/www/html/redmine-3.4.11/plugins/redmine_smile_base-master/lib/smile_redmine_i18n.rb:287:in `prepended'
/var/www/html/redmine-3.4.11/plugins/redmine_smile_base-master/init.rb:59:in `prepend'
/var/www/html/redmine-3.4.11/plugins/redmine_smile_base-master/init.rb:59:in `prepend_in'
/var/www/html/redmine-3.4.11/plugins/redmine_smile_base-master/init.rb:157:in `block in <top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:446:in `instance_exec'
/var/lib/gems/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:446:in `block in make_lambda'
/var/lib/gems/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:192:in `block in simple'
/var/lib/gems/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:504:in `block in call'
/var/lib/gems/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:504:in `each'
/var/lib/gems/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:504:in `call'
/var/lib/gems/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/var/lib/gems/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
/var/lib/gems/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/lib/gems/2.3.0/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
/var/lib/gems/2.3.0/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
/var/lib/gems/2.3.0/gems/railties-4.2.11.1/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
/var/lib/gems/2.3.0/gems/railties-4.2.11.1/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/2.3.0/gems/railties-4.2.11.1/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/2.3.0/gems/railties-4.2.11.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/lib/gems/2.3.0/gems/railties-4.2.11.1/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/2.3.0/gems/railties-4.2.11.1/lib/rails/application.rb:352:in `initialize!'
/var/www/html/redmine-3.4.11/config/environment.rb:14:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
/var/lib/gems/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.3.0/gems/railties-4.2.11.1/lib/rails/application.rb:328:in `require_environment!'
/var/lib/gems/2.3.0/gems/railties-4.2.11.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/var/lib/gems/2.3.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

```

**Comment by sherpadawan** [comment]
Any advice as requirements (gem i18N > 0.7 ? )
see https://www.redmine.org/issues/29946 ?

**Comment by Utopism** [comment]
Hi,
This message tells that the redmine_smile_base plugin could not override **I18n** with :
prepend_in(Redmine::I18n, Smile::RedmineOverride::I18nOverride::Enhancements)

You have to rename the **redmine_smile_base-master** folder to **redmine_smile_base** (this is a convention necessary for all Redmine plugins).

**Comment by sherpadawan** [comment]
Thank you !

**Comment by sherpadawan** [comment]
Pushing a release archive with the proper directory name would be a good thing ?

**Comment by Utopism** [comment]
I don't think so, as it is precised in the Redmine plugin install howto, installing with git clone will create the right folder.
https://www.redmine.org/projects/redmine/wiki/Plugins
